name: CI-CD

on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtenção do codigo do projeto
        uses: actions/checkout@v4
      
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção e envio da imagem para o Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            valdinei/fake-shop:latest
            valdinei/fake-shop:v${{ github.run_number }}
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Obtenção do codigo do projeto
        uses: actions/checkout@v4

      - name: Autenticar na AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configuração Kubectl
        run: aws eks update-kubeconfig --name desafio-eks
      
      - name: Deploy dos manifestos do kubernetes
      - uses: Azure/k8s-deploy@v5
        with:
          manifests: |
              ./k8s/deployment.yaml
          images: |
              valdinei/fake-shop:v${{ github.run_number }}